export { GOLDEN_CASE_REGISTRY } from '@/domains/golden/registry';
export { HKO_PUBLISHED_REFERENCE_GOLDEN_CASES } from '@/domains/golden/published-references';
export {
  OWNER_DECISION_RESOLUTION_CONTRACT_VERSION,
  OWNER_DECISION_RESOLUTION_STATUS,
  OWNER_DECISION_RESOLUTION_TARGET_BATCH,
  OWNER_DECISION_RESOLUTION_AUDIT_CASE_IDS,
  PUBLIC_BIRTH_DATE_RANGE_DECISION_ID,
  P5_A5A_OWNER_DECISION_RESOLUTION_CASES,
  getOwnerDecisionResolutionValidationErrors,
  getOwnerDecisionResolutionRegistryValidationErrors,
  getOwnerDecisionResolutionVersionedValidationErrors,
  getOwnerDecisionResolutionVersionedRegistryValidationErrors,
  validateOwnerDecisionResolution,
  validateOwnerDecisionResolutionRegistry,
  validateOwnerDecisionResolutionVersioned,
  validateOwnerDecisionResolutionVersionedRegistry,
  type OwnerDecisionResolution,
  type OwnerDecisionResolutionAuditCaseId,
  type OwnerDecisionResolutionVersioned,
} from '@/domains/golden/owner-decision-resolution';
export {
  BOUNDARY_INPUT_AUDIT_CONTRACT_VERSION,
  BOUNDARY_AUDIT_CATEGORIES,
  BOUNDARY_AUDIT_MODULES,
  BOUNDARY_AUDIT_STATUSES,
  BOUNDARY_AUDIT_TARGET_BATCHES,
  P5_BOUNDARY_INPUT_AUDIT_CASES,
  getBoundaryInputAuditValidationErrors,
  validateBoundaryInputAuditCase,
  validateBoundaryInputAuditRegistry,
  type BoundaryAuditCategory,
  type BoundaryAuditModule,
  type BoundaryAuditStatus,
  type BoundaryAuditTargetBatch,
  type BoundaryInputAuditCase,
} from '@/domains/golden/boundary-input-contract';
export {
  BOUNDARY_INPUT_RESOLUTION_AUDIT_CASE_IDS,
  BOUNDARY_INPUT_RESOLUTION_CONTRACT_VERSION,
  BOUNDARY_INPUT_RESOLUTION_V1_AUDIT_CASE_IDS,
  BOUNDARY_INPUT_RESOLUTION_V1_CONTRACT_VERSION,
  BOUNDARY_INPUT_RESOLUTION_V2_AUDIT_CASE_IDS,
  BOUNDARY_INPUT_RESOLUTION_V2_CONTRACT_VERSION,
  BOUNDARY_INPUT_RESOLUTION_V3_AUDIT_CASE_IDS,
  BOUNDARY_INPUT_RESOLUTION_V3_CONTRACT_VERSION,
  BOUNDARY_INPUT_RESOLUTION_V4_AUDIT_CASE_IDS,
  BOUNDARY_INPUT_RESOLUTION_V4_CONTRACT_VERSION,
  BOUNDARY_INPUT_RESOLUTION_V5_AUDIT_CASE_IDS,
  BOUNDARY_INPUT_RESOLUTION_V5_CONTRACT_VERSION,
  BOUNDARY_INPUT_RESOLUTION_STATUS,
  P5_A4B_INPUT_RESOLUTION_CASES,
  P5_A4B_INPUT_RESOLUTION_V2_CASES,
  P5_A4B_INPUT_RESOLUTION_V3_CASES,
  P5_A4B_INPUT_RESOLUTION_V4_CASES,
  P5_A4B_INPUT_RESOLUTION_V5_CASES,
  getBoundaryInputResolutionRegistryValidationErrors,
  getBoundaryInputResolutionV2RegistryValidationErrors,
  getBoundaryInputResolutionV3RegistryValidationErrors,
  getBoundaryInputResolutionV4RegistryValidationErrors,
  getBoundaryInputResolutionV5RegistryValidationErrors,
  getBoundaryInputResolutionValidationErrors,
  getBoundaryInputResolutionV2ValidationErrors,
  getBoundaryInputResolutionV3ValidationErrors,
  getBoundaryInputResolutionV4ValidationErrors,
  getBoundaryInputResolutionV5ValidationErrors,
  getBoundaryInputResolutionVersionedRegistryValidationErrors,
  getBoundaryInputResolutionVersionedValidationErrors,
  validateBoundaryInputResolution,
  validateBoundaryInputResolutionRegistry,
  validateBoundaryInputResolutionV2,
  validateBoundaryInputResolutionV2Registry,
  validateBoundaryInputResolutionV3,
  validateBoundaryInputResolutionV3Registry,
  validateBoundaryInputResolutionV4,
  validateBoundaryInputResolutionV4Registry,
  validateBoundaryInputResolutionV5,
  validateBoundaryInputResolutionV5Registry,
  validateBoundaryInputResolutionVersioned,
  validateBoundaryInputResolutionVersionedRegistry,
  type BoundaryInputResolution,
  type BoundaryInputResolutionAuditCaseId,
  type BoundaryInputResolutionV1,
  type BoundaryInputResolutionV2,
  type BoundaryInputResolutionV2AuditCaseId,
  type BoundaryInputResolutionV3,
  type BoundaryInputResolutionV3AuditCaseId,
  type BoundaryInputResolutionV4,
  type BoundaryInputResolutionV4AuditCaseId,
  type BoundaryInputResolutionV5,
  type BoundaryInputResolutionV5AuditCaseId,
  type BoundaryInputResolutionVersioned,
} from '@/domains/golden/boundary-input-resolution';
export {
  getGoldenCaseValidationErrors,
  validateGoldenCase,
  validateGoldenCaseRegistry,
} from '@/domains/golden/validator';
export {
  GOLDEN_CASE_CONTRACT_VERSION,
  GOLDEN_MODULES,
  GOLDEN_SOURCE_TYPES,
  GOLDEN_VALIDATION_CLASSES,
  INDEPENDENT_VERIFICATION_SCOPES,
  INDEPENDENT_VERIFICATION_STATUSES,
  type GoldenCase,
  type GoldenModule,
  type GoldenSourceReference,
  type GoldenSourceType,
  type GoldenValidationClass,
  type IndependentVerification,
  type JsonObject,
  type JsonValue,
} from '@/domains/golden/types';
